Update backup scripts

diff --git a/commands/backup b/commands/backup
--- a/commands/backup
+++ b/commands/backup
@@ -11,56 +11,61 @@ Flags:
   -h, --help            Print this help text and exit.
 
 Level 1 Commands:
-  alpha                 Backup all files from HOME to Alpha (SSD).
-  beta                  Backup all files from HOME to Beta (DHD).
-  borg                  Backup essential files from HOME to rsync.net.
+  alpha                 Backup HOME to Alpha (SSD).
+  beta                  Backup HOME to Beta (DHD).
+  borg                  Backup HOME to Borg.
 
 Level 2 Commands:
-  a2b, alpha2beta       Backup content from Alpha (SSD) to Beta (DHD).
-  b2g, beta2gamma       Backup content from Beta (DHD) to Gamma (PHD).
+  a2b, alpha2beta       Backup Alpha (SSD) to Beta (DHD).
+  b2g, beta2gamma       Backup Beta (DHD) to Gamma (PHD).
 
 Level 3 Commands:
-  b2k, beta2kappa       Backup content from Beta (DHD) to Kappa (PHD).
-  b2i, beta2iota        Backup content from Beta (DHD) to Iota (PHD).
+  b2k, beta2kappa       Backup  Beta (DHD) to Kappa (PHD).
+  b2i, beta2iota        Backup  Beta (DHD) to Iota (PHD).
+
+Admin Commands:
+  init-borg             Initialize a new Borg repository.
 EOF
 }
 
-if test "$#" = "0"; then
+if test $# -eq 0; then
     print_help
     exit 0
 fi
 
-cmd="$1"
-shift
-
-case "$cmd" in
-    alpha)
-        ~/.dotfiles/scripts/backup-to-disk.sh Alpha
-        ;;
-    beta)
-        ~/.dotfiles/scripts/backup-to-disk.sh Beta
-        ;;
-    borg)
-        ~/.dotfiles/scripts/backup-to-borg.sh "$@"
-        ;;
-    b2k|beta2kappa)
-        ~/.dotfiles/scripts/backup-beta2kappa.sh
-        ;;
-    b2i|beta2iota)
-        ~/.dotfiles/scripts/backup-beta2iota.sh
-        ;;
-    a2b|alpha2beta)
-        ~/.dotfiles/scripts/backup-alpha2beta.sh
-        ;;
-    b2g|beta2gamma)
-        ~/.dotfiles/scripts/backup-beta2gamma.sh
-        ;;
-    ""|--help|-h)
-        print_help
-        exit 0
-        ;;
-    *)
-        echo "Error: unsupported command."
-        exit 1
-        ;;
-esac
+for target in "$@"; do
+    case "$target" in
+        alpha)
+            ~/.dotfiles/scripts/backup-to-disk.sh Alpha
+            ;;
+        beta)
+            ~/.dotfiles/scripts/backup-to-disk.sh Beta
+            ;;
+        borg)
+            ~/.dotfiles/scripts/backup-to-borg.sh
+            ;;
+        b2k|beta2kappa)
+            ~/.dotfiles/scripts/backup-beta2kappa.sh
+            ;;
+        b2i|beta2iota)
+            ~/.dotfiles/scripts/backup-beta2iota.sh
+            ;;
+        a2b|alpha2beta)
+            ~/.dotfiles/scripts/backup-alpha2beta.sh
+            ;;
+        b2g|beta2gamma)
+            ~/.dotfiles/scripts/backup-beta2gamma.sh
+            ;;
+        init-borg)
+            ~/.dotfiles/scripts/init-borg.sh
+            ;;
+        ""|--help|-h)
+            print_help
+            exit 0
+            ;;
+        *)
+            echo "error: unsupported target '$target'"
+            exit 1
+            ;;
+    esac
+done
